### ISSUE TITLE
Named routes

### ISSUE THREAD

**Issue by jhuenges** [arillo/meteor-flow-router-helpers#1]
Since version 1.2.0 of FlowRouter named routes are supported. Luckily [it seems your package still works](https://github.com/meteorhacks/flow-router#using-route-name-instead-of-the-pathdef), but I guess it would be great to mention it in the README.md

**Comment by banglashi** [comment]
hi @jhuenges,
thanks for pointing that out. I updated the Readme.md to reflect that.
