### ISSUE TITLE
Please change to "kadira:flow-router"?

### ISSUE THREAD

**Issue by thearabbit** [arillo/meteor-flow-router-helpers#10]
Please change to "kadira:flow-router"?

**Comment by banglashi** [comment]
Hi @thearabbit, since it depends on zimme:activeroute we will need to wait to be updated first. I saw you already created an issue for this here https://github.com/zimme/meteor-active-route/issues/36 
Let me know when it's done and I will upgrade too.

**Comment by zimme** [comment]
zimme/meteor-active-route#37

**Comment by lsunsi** [comment]
It's done

**Comment by zimme** [comment]
`zimme:active-route@2.3.0` released. Support for `kadira:flow-router`

**Comment by thearabbit** [comment]
Look great :+1:

**Comment by banglashi** [comment]
is updated in version 0.4.0. Let me know if it works as expected.

**Comment by thearabbit** [comment]
Please correct doc.

**Comment by banglashi** [comment]
forgot that. Done now.

**Comment by abernix** [comment]
Works great for me on both `flow-router` packages.  Thanks very much for your work. :)
