### ISSUE TITLE
Can you depreciate the use of meteorhacks:flow-router?

### ISSUE THREAD

**Issue by sergical** [arillo/meteor-flow-router-helpers#14]
It loads up both versions into my `versions` file which then results in an error in my app `There is no route for the path: /` or for any other routes.

**Comment by banglashi** [comment]
it shouldn't do that, since the dependency is defined as weak. Perhaps you have another package still depending on meteorhacks:flow-router in your project?

**Comment by sergical** [comment]
Thanks @banglashi just wanted to confirm that `weak` didn't actually pull it into my versions. Great work on the package!
