### ISSUE TITLE
Could I pass dynamic values to query parameters?

### ISSUE THREAD

**Issue by sungwoncho** [arillo/meteor-flow-router-helpers#17]
I would like to use `pathFor` helper to create a path with a query parameter that depends on the data context.

```
{{pathFor 'myTemplate' query='foo=myDataContext.something'}}
```

Obviously this does not work because `myDataContext.something` is interpreted as a string, not a variable.

I've tried to concatenate as follows:

```
{{pathFor 'myTemplate' query='foo=' + myDataContext.something}}
```

But it did not work. Any ways to achieve this?

**Comment by banglashi** [comment]
Out of the box, I don't think so, unless you create a TemplateHelper that will build up your query for you and than just pass that along. For example:

``` javascript
Template.templateName.helpers({
  getQueryParams: function(){
    var query = {
      test: 'test',
      param1: 'search'
    };
    return FlowRouter._qs.stringify(query);
  }
});
```

``` handlebars
<template name="templateName">
  {{pathFor 'myTemplate' query=getQueryParams}}
</template>
```

Another option:
I could check the type of the query parameter and stringify it if it is an object, but you wouldn't have selective control if which key/value pairs to add.

Let me know if it helps you.

**Comment by zimme** [comment]
I think there might be another way of doing this with the next Meteor version too, as I believe it implements support for nested helpers or something like that. But I'm not sure.

**Comment by sungwoncho** [comment]
@banglashi Thanks, your solution seems valid. I resorted to a simpler solution of using regular parameters.

**Comment by sungwoncho** [comment]
@banglashi I am back in this issue. Your solution works but the query is fixed.

When I try to make it dynamic by doing this, I get an error:

``` javascript
Template.templateName.helpers({
  getQueryParams: function(key, val){
    var query = {
      key: val
    };
    return FlowRouter._qs.stringify(query);
  }
});
```

``` html
<template name="templateName">
  {{pathFor 'myTemplate' query=getQueryParams query= getQueryParams(myKey, myVal)}}
</template>
```

Meteor throws `Expected space` while building the template. Any suggestions?

**Comment by banglashi** [comment]
@sungwoncho do you want to append the current available queryParams to the link?
 For that you can just do:

``` javascript
    Template.templateName.helpers({
      getQueryParams: function(){
        var current = FlowRouter.current();
        return FlowRouter._qs.stringify(current.queryParams);
      }
    });
```

and in the template:

``` handlebars
<template name="templateName">
  {{pathFor 'myTemplate' query=getQueryParams}}
</template>
```

**Comment by sungwoncho** [comment]
That's a good solution but my problem is different. I would like to construct queryParams on the fly (hence, dynamic).

contrite example:

``` javascript
Template.myTemplate.helpers({
  currentPost: function() {
    return Post.findOne();
  }
});
```

```
<template name="myTemplate">
  {{pathFor 'post' query='version=currentPost.version'}}
</template>
```

**Comment by banglashi** [comment]
@sungwoncho you can then do something like this

``` javascript
Template.myTemplate.onCreated(function(){
  this.currentPost = Post.findOne();
});
Template.myTemplate.helpers({
  getQueryParams: function(){
    var params = {
      version: Template.instance().currentPost.version
    };
    return FlowRouter._qs.stringify(params);
  }
});
```

``` handlebars
<template name="myTemplate">
  {{pathFor 'post' query=getQueryParams}}
</template>
```

**Comment by sean-stanley** [comment]
To change dynamic query params I resorted to using a template event handler.

Here is a sample in CoffeeScript ( I suppose I should start using es6 soon though ):

```
Template.catalogHome.events
  "click .select-category": (event, template) ->
    event.preventDefault()
    target = $ event.target
    FlowRouter.setQueryParams {all:true, category1: target.data('param'), pages:null}
```

In this instance I always knew which param I was modifying and used a data attribute in my template to set the controls.

If you can take advantage of having the keys and values of your possible dynamic params in your data context you can do something like this:

```
"click .category-button": (event, template) ->
    queryParams = {all:true} #any static defaults we want applied
    queryParams[@param] = @value #taken from this.param and this.value in data context
    FlowRouter.go "/store", null, queryParams
```

I had a list of tags that were the categories repeated above with {{each}} meaning every button had the proper data context.

Hopefully these ideas are helpful and if there are serious problems with my approach someone will let me know as well.

**Comment by raza2022** [comment]
any updated on it I stuck with same @sungwoncho have you resolve it within template?
