### ISSUE TITLE
Could I use helper in helper ({{> afQuickField name='myId' value={{param 'id'}} }})?

### ISSUE THREAD

**Issue by thearabbit** [arillo/meteor-flow-router-helpers#19]
Could I use helper in helper

``` js
{{> afQuickField name='myId' value={{param 'id'}} }}
```

**Comment by zimme** [comment]
Meteor does not support nested helpers yet, I believe there's support for it in the next Meteor version but I'm not completely sure.

**Comment by zimme** [comment]
You can probably setup a helper named `id` which returns the id param without taking an argument.

``` handlebars
{{> afQuickField name='myId' value=id }}
```

``` js
Template.<name>.helpers({
  id: function() { ... return id param ... }
}
```

**Comment by thearabbit** [comment]
Thanks for your helping.
