### ISSUE TITLE
Passing data to routes without including it in the path

### ISSUE THREAD

**Issue by mbabauer** [arillo/meteor-flow-router-helpers#23]
So, I have been using Flow-Router for a bit now, but until now I have never needed to do this, and now I am stuck.  What I'd like to do is pass in values to the params, but I don't want them in the URL at all.

What I am trying to accomplish is to simulate an anchor tag jump on the page.  In my case, I have some fancy JS "scrollTo" code logic built into the page, and I want to be able to pass in a hidden value as part of the data to trigger the template code to scroll to that location, like like a #anchor does.

The problem is that the routes only seem to accept params when they appear in the URL path somewhere.  Is there a way I could use the pathFor to pass in custom params, or am I going down a dead-end path here?

**Comment by banglashi** [comment]
As I understand, flow-router doesn't allow you for hidden parameters. 
Have you thought of just using Session to pass on the parameters?

**Comment by mbabauer** [comment]
I am using `{{pathFor}}` to generate the link, so Session wouldn't work.  However, I did get things working in a round-about way.

First I set up my routes like this:

``` javascript
FlowRouter.route('/', {
  name: 'home',
  action: function(params, queryParams) {
    BlazeLayout.render('MasterLayout', { main: 'home' });
  }
});

// Put all other routes here...

// This route MUST be last!
FlowRouter.route('/:scrollTo', {
  name: 'home_scroll',
  action: function(params, queryParams) {
    BlazeLayout.render('MasterLayout', { main: 'home', data: {scrollTo: '#' + params.scrollTo} });
  }
});
```

Then in my header template I pass in the ID of the item I want to scroll to like so:

``` javascript
<a id="menuServices" href="{{pathFor 'home_scroll' scrollTo='services'}}">Services</a>
```

In the `home` template, I created a helper that will call the scroll code:

``` javascript
Template.home.helpers({
    initiateScrollTo: function(scrollTo) {
        Tracker.autorun(function() {
            Tracker.afterFlush(function() {
                if (scrollTo) {
                    scrollToTarget(scrollTo);
                }
            });
        });
    }
});
```

And finally in the home template HTML I call the template using `{{initiateScrollTo scrollTo}}`.  The big trick is to use `Tracker.afterFlush()` to ensure that the scroll code only runs after the page has fully rendered.  I tried using the `onRendered`, but the issue there is that it only gets called once, which means your link only works once.

Ultimately, this works out nice because you end up with actual URLs that point to the sections.
