### ISSUE TITLE
pathFor ignores every param except the last one for an array

### ISSUE THREAD

**Issue by cbelsole** [arillo/meteor-flow-router-helpers#3]
I tried the path helper:

``` javascript
{{pathFor 'somePath' query='some[]=param&some[]=otherParam&some[]=yetAnotherParam'}}
```

It only ever used the last param in the string. The path ends up as: 

```
somePath?some%5B%5D=yetAnotherParam
```

Edit:
This may actually be a Flow Router problem. I just did:

``` javascript
FlowRouter.path('somePath', {}, {'some[]': 1, 'some[]': 2})
```

and I got:

```
/somePath/?some%5B%5D=2"
```

**Comment by cbelsole** [comment]
Never mind. That is just how JS objects work. Duh. For anyone coming after me you can create such a route with this

``` javascript
FlowRouter.path('somePath', {}, {'some': [1, 2]})
```

**Comment by cbelsole** [comment]
Closed prematurely. I think there is still an issue here. Possibly you should be able to pass the params hash down since it will ignore anything but the last parameter in the array.

**Comment by banglashi** [comment]
Hi @cbelsole,

thanks for pointing that out. I am now using the query lib from page.js referenced in the internal variable of FlowRouter _qs. It should now work as expected. Just update to version 0.1.4. If in the future flow-router changes the access I will update it asap.
