### ISSUE TITLE
error for isActivePath

### ISSUE THREAD

**Issue by michaelevensen** [arillo/meteor-flow-router-helpers#4]
```
.reactiveCurrent() is deprecated. Use .watchPathChange() instead
```

When using it like this:

```
 <li class="{{isActivePath regex='invites$'}}"><a href="{{pathFor 'dashboardInvites'}}">Invites</a></li>
```

**Comment by banglashi** [comment]
Hi @michaelevensen,
thanks for the info. There is now version arillo:flow-router-helpers@0.1.5 working with flow-router@1.8.0
https://atmospherejs.com/arillo/flow-router-helpers

**Comment by michaelevensen** [comment]
@banglashi Wow that was quick, thanks!
