### ISSUE TITLE
Add {{#linkTo route="home"}}...{{/linkTo}} helper

### ISSUE THREAD

**Issue by zimme** [arillo/meteor-flow-router-helpers#6]
`iron:router` have this helper and it's quite handy =)

``` html
{{#linkTo route="home"}}
  Go home
{{/linkTo}}
<a href="/">Go home</a>
```

**Comment by peterchoo** [comment]
:+1: for this.

**Comment by banglashi** [comment]
Hi @zimme, hi @peterchoo,

I will try to take a look this weekend. Will keep you updated.

**Comment by banglashi** [comment]
This is implemented, just waiting for a reply to another issue to publish a new version. Do you know if there is any way I can define a custom content block directly in js? (Without adding the .html)

**Comment by zimme** [comment]
It seems like you can use `view.templateContentBlock` and `view.contentElseBlock` which will give you a `Template` for the content.

**Comment by zimme** [comment]
I'll close this as this seems to be implemented already.
