### ISSUE TITLE
activeRoute is not updated if I go or redirect to another route

### ISSUE THREAD

**Issue by derwaldgeist** [arillo/meteor-flow-router-helpers#9]
I'm using activeRoute to highlight elements in my navigation bar. This works if the user clicks on the navigation bar elements and no redirect is taking place. But if I use FlowRouter.go() or redirect() in a router trigger, the navigation bar does not get updated. It will only update if I reload the browser. How can I make Meteor adjust the state of my navigation bar on redirects?

**Comment by banglashi** [comment]
Hi @derwaldgeist, I just try reproducing your issue in one of my apps by running FlowRouter.go('profile') or FlowRouter.redirect('profile') directly in the console. The menu highlights did work properly. Are you doing your redirects in some special place?

**Comment by satyavh** [comment]
Agree, non of these helpers work. activeRoute, activePath, the all don't get updated
for example:

```
        li(class="{{isActiveRoute 'home'}}")
          a(href="{{pathFor 'home'}}")
            span.fa.fa-qrcode
            |  Home
```

Clicking on this link doesn't make it active

**Comment by zimme** [comment]
I'll try and reproduce this and if I can I'll open an issue with flow-router because then it's not reactively updating the path info when flow-router intercepts link clicks

**Comment by zimme** [comment]
I can't reproduce this at all. Please provide a reproduction repo if this is still a problem and I'll look into it.

**Comment by satyavh** [comment]
Yesterday this suddenly started to work. I really have no idea why, didn't change that particular code. 
Maybe some package in the way, or some package updated. But it works fine now. 
Thanks for checking

**Comment by derwaldgeist** [comment]
I now provided a concrete sample here:
https://github.com/zimme/meteor-active-route/issues/40
